[package]
name = "tessera-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tessera-core = { path = "../crates/tessera-core" }
tracing = { workspace = true }
tauri = { version = "2", features = [] }

[build-dependencies]
tauri-build = { version = "2", features = [] }
