[package]
name = "tessera-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tessera-error = { path = "../tessera-error" }
r2d2 = { workspace = true }
r2d2_sqlite = { workspace = true }
rusqlite = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
