[package]
name = "tessera-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tessera-error = { path = "../tessera-error" }
tessera-manifest = { path = "../tessera-manifest" }
tessera-store = { path = "../tessera-store" }
tessera-sandbox = { path = "../tessera-sandbox" }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = "3"
